name: skadnetwork_plugin
description: A simple Flutter plugin to set SKAdNetwork conversion values.
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SkadnetworkPlugin
